version: "3.8"

services:
  identity-pg:
    image: postgres:alpine3.18
    ports:
      - "5001:5001"
    environment:
      POSTGRES_USER: shef
      POSTGRES_PASSWORD: snapshare
      POSTGRES_DB: SnapShare
      PGPORT: 5001
    restart: always
  
  identity-redis:
    image: redis:alpine3.18
    ports: 
      - "5002:5002"
    command:
      redis-server --port 5002 --requirepass snapshare
    restart: always

  identity-service:
    build: ./IdentityService
    ports:
      - "5100:5100"
      - "5010:5010"
    restart: always
    depends_on:
      - identity-pg
      - identity-redis


  share-redis:
    image: redis:alpine3.18
    ports:
      - "4002:4002"
    command:
      redis-server --port 4002 --requirepass snapshare
    restart: always

  share-service:
    build: ./ShareService
    ports:
      - "4000:4000"
    volumes: 
      - ./ShareService/tmp:/tmp
    restart: always
    depends_on:
      - share-redis
  
  spa-client:
    build: ./SPA
    ports:
      - "8080:8080"
    restart: always

  gateway:
    image: nginx:alpine3.18
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./SPA/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: always
    depends_on:
      - identity-service
      - share-service
      - spa-client
